import type { NextPage } from "next";
import Head from "next/head";

import LoginForm from "../_components/loginForm";
import { WavyBackground } from "@/components/ui/wavy-background";
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Image from "next/image";
//           <LoginForm />
const Register: NextPage = async () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="h-screen w-full lg:grid lg:min-h-[600px] lg:grid-cols-2">
          <div className="flex items-center justify-center py-12">
            <LoginForm />
          </div>
          <div className="bg-muted hidden overflow-hidden lg:block">
            {/* <WavyBackground  /> */}
          </div>
        </div>
      </main>
    </>
  );
};

export default Register;
