import type { NextPage } from "next";
import Head from "next/head";

import LoginForm from "../_components/loginForm";

const Register: NextPage = async () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center">
        <div>
          <div>Login</div>
          <LoginForm />
        </div>
      </main>
    </>
  );
};

export default Register;
