import type { NextPage } from "next";
import Head from "next/head";
import { getServerAuthSession } from "@/server/auth";
import RegisterForm from "../_components/registerForm";
// import SignOut from "../_components/signOut";
import SignOut from "../_components/signOut";

const Register: NextPage = async () => {
  const session = await getServerAuthSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center">
        {session ? (
          <div>
            You are already logged in
            <div>{JSON.stringify(session)}</div>
            <SignOut />
          </div>
        ) : (
          <div>
            <div>Sign up</div>
            <RegisterForm />
          </div>
        )}
      </main>
    </>
  );
};

export default Register;
